# Generated by Django 4.2.3 on 2023-08-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('edition', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Mystery', 'mystery'), ('Thriller', 'Thriller'), ('Sci-Fo', 'Sci-Fi'), ('Humor', 'Humor'), ('Horror', 'Horror')], max_length=30)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('last_published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
